name: Alpha Bit Soup
description: Programming and Business in One Delightful Blend
url: http://www.alphabitsoup.net

pygments: true

exclude: ["vendor"]

permalink: /:year/:month/:day/:title/

#gems: ['jekyll-less']
 # This will require each of these gems automatically.